### ISSUE TITLE
iam tests failing locally

### ISSUE THREAD

**Issue by sirpy** [gitcoinco/dPopp#266]
when running iam tests from a fresh install of main branch two tests are failing
digging deeper the error that is returned is "unable to get verification method" using grep the only place this string seems to appear is at some did wasm module
```
POST /verify › handles valid challenge requests

    expected 200 "OK", got 400 "Bad Request"

      86 |       .send({ challenge, payload })
      87 |       .set("Accept", "application/json")
    > 88 |       .expect(200)
         |        ^
      89 |       .expect("Content-Type", /json/);
      90 |
      91 |     // check for an id match on the mocked credential
```
```
 ● POST /verify › handles valid challenge requests

    expected 200 "OK", got 400 "Bad Request"

      86 |       .send({ challenge, payload })
      87 |       .set("Accept", "application/json")
    > 88 |       .expect(200)
         |        ^
      89 |       .expect("Content-Type", /json/);
      90 |
      91 |     // check for an id match on the mocked credential

      at __tests__/index.test.ts:88:8
      at __tests__/index.test.ts:31:71
```

**Comment by sirpy** [comment]
@shavinac yeah i figured that out eventually. thanks
